# Generated by Django 3.1.7 on 2021-03-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210322_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
